### PR TITLE
fix: own function access keys without write permission

### LINKED ISSUE #897: Unable to deploy with near-bos-cli
**Affected Portal:**
Select one: DevHub ( might affect all )

**Description:**
The DevHUB deployment pipeline currently fails with the following error from `bos-cli`

```bash
Error: 
Your console command:
bos components deploy devhub.near sign-as devhub.near network-config mainnet sign-with-plaintext-private-key --signer-public-key ed25519:3eLvVvLmB4gfJaZWYCwNLQXHhkxzJNvrdX5V8YCz1WMV --signer-private-key *** send
   0: ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key
```

Since we saw that it is possible to deploy by calling `set` directly on `social.near` using `near-cli-rs` as done in https://github.com/NEAR-DevHub/neardevhub-bos/pull/894, we know that the error message from `bos-cli` is wrong. `bos-cli` is estimating wrong when it comes to the storage deposit required.

Also 10 NEAR was deposited for devhub to increase storage ( see transactions [3bnAqyNbtnkq7D67t6kGoTEFQG9gyEvYr71GEzQA9oaS](https://nearblocks.io/txns/3bnAqyNbtnkq7D67t6kGoTEFQG9gyEvYr71GEzQA9oaS),  [41hZN6kWEdYgr6A3hHxhsavhJRJoQLUPsfzbfNKTzfGo](https://nearblocks.io/txns/41hZN6kWEdYgr6A3hHxhsavhJRJoQLUPsfzbfNKTzfGo),
[233YEPkmLKcFrLByHv1bXWTYT1yndAGQJwrbdHmxDL7j](https://nearblocks.io/txns/233YEPkmLKcFrLByHv1bXWTYT1yndAGQJwrbdHmxDL7j),
[ATbWDMxPHuNQ8gdESBHWw14qUCddEEXsw8jpb4Eaf6tx](https://nearblocks.io/txns/ATbWDMxPHuNQ8gdESBHWw14qUCddEEXsw8jpb4Eaf6tx) and [DL6pu1tugLmAuHkx6ceHhCSzntWYbf9jNAn7CGL6BLWH](https://nearblocks.io/txns/DL6pu1tugLmAuHkx6ceHhCSzntWYbf9jNAn7CGL6BLWH)

) with the result of increased storage, as we can see when running 

```bash
 bos social-db prepaid-storage view-balance devhub.near network-config mainnet now
storage balance for <devhub.near>:
 available:        1.8 MB   (17.72 NEAR [  17714790000000000000000014 yoctoNEAR])
 total:            2.7 MB   (27.11 NEAR [  27100000000000000000000014 yoctoNEAR])
```

Still `bos components deploy` fails with the error message about insufficient deposit for storage.

**User Type:**
Specify:  Other

**Reproduction Steps**
Any deployment with `bos cli`

**Expected behavior**
BOS cli should estimate storage deposit requirements correctly, or not estimate at all and let the deployment transaction fail instead.

**Visual Reference**
If applicable, add screenshots or video recording to help explain your problem.

**Priority**
Select One: High (P1) – Unexpected error or behavior ( All deployments are affected, it is possible to work around it by calling `set` directly on the `social.near` contract without using bos cli ).

**Environment Details**
N/A

**Additional Context**
N/A

### PR DESCRIPTION
**Pull request by petersalomonsen**
As can be seen if running the tests without the fix, we get the error message `ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key` if using a function access key that does not have explicit write permission, but comes from the account that we want to write to. This should not fail, and this PR reproduces and fixes the issue.

Here is the output of running the unit tests without the fix:

```bash
test tests::test_get_deposit_other_account_no_explicit_write_permission ... ok
test tests::test_get_deposit_own_account_explicit_write_permission ... ok
test tests::test_get_deposit_own_account_no_explicit_write_permission ... FAILED
test tests::test_get_deposit_same_account_function_access_key_with_required_deposit ... ok
test tests::test_get_deposit_write_permission_function_access_key_with_required_deposit ... ok

failures:

---- tests::test_get_deposit_own_account_no_explicit_write_permission stdout ----
Error: ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key

Location:
    src/lib.rs:191:17
thread 'tests::test_get_deposit_own_account_no_explicit_write_permission' panicked at src/lib.rs:465:17:
get_deposit should not fail when using a public key belonging to the target account, even without explicit write permission. Error Message:
ERROR: Social DB requires more storage deposit, but we cannot cover it when signing transaction with a Function Call only access key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_get_deposit_own_account_no_explicit_write_permission
```

In addition this PR adds github codespaces setup, and a workflow for running the unit tests. The "code-style" CI workflow is also updated to use `ubuntu-latest` and `rust-cache` because it failed with the current setup.

fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/897

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@race-of-sloths Please include this PR

**Comment by race-of-sloths** [comment]
@petersalomonsen Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
You are true leader! Other sloths hot on your heels, keep moving!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/petersalomonsen)





<details><summary>Current status: <i>executed</i></summary>

| Reviewer | Score |
|--------|--------|
| @frol  | 8 |

**The average score is 8**

@petersalomonsen check out your results on the [Race of Sloths Leaderboard!](https://race-of-sloths.com/leaderboard) and in the [profile](https://race-of-sloths.com/profile/petersalomonsen)

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/petersalomonsen)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by frol — APPROVED** [review]
@petersalomonsen Thank you for authoring the fix and introducing the tests!

@race-of-sloths score 8

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

**Comment by petersalomonsen** [comment]
@frol "code-style" and "unit-test" CI workflows are now updated to use `ubuntu-latest` and `rust-cache` because the existing setup failed to compile ( as you can see from previous runs ). 

Al CI workflows pass in the [PR to my own fork](https://github.com/petersalomonsen/near-socialdb-client-rs/pull/1)

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 8!
You have received 110 (80 base + 20 weekly bonus + 10 monthly bonus) Sloth points for this contribution


Congratulations @petersalomonsen! Your PR was highly scored and you completed another monthly streak! To keep your monthly streak make another pull request next month and get 8+ score for it

**Pull request merged**
